routes/web.php
Route::resource('/photgrapherfeedback','Photographer\FeedbackController');
Route::resource('/photographerpayments', 'Photographer\PaymentController');
Route::resource('/photographergallery', 'Photographer\GalleryController');

Route::get('/photographergallery/{id}/index/delete_image/{pcgalleryid}','Photographer\GalleryController@delete_image');

Route::resource('/admindashboard', 'Admin\DashboardController');
// Route::resource('/adminfaq', 'Admin\FaqController');
Route::resource('/adminprofiles', 'Admin\ProfilesController');
Route::resource('/adminbusinesssetting', 'Admin\BusinesssettingController');
Route::resource('/admincategory','Admin\CategoryController');
Route::resource('/adminposts', 'Admin\PostsController');
Route::resource('/adminaboutus', 'Admin\AboutusController');
Route::resource('/admincontactus', 'Admin\ContactusController');
Route::resource('/adminhowitworks', 'Admin\HowitworksController');
Route::resource('/adminhomephotographers', 'Admin\HomephotographersController');
Route::resource('/adminhomecomingsoons', 'Admin\HomecomingsoonsController');
Route::resource('/postsevent', 'Admin\PosteventController');

Route::resource('/admincontacts', 'Admin\ContactsController');
// Route::get('/adminposts', 'PostsController@co_destroy')
Route::resource('/admincustomer', 'Admin\CustomersController');
Route::resource('/admincustomers', 'Admin\CustomerRegisterController');
Route::resource('/admincategory','Admin\CategoryController');
Route::get('/admincategory/{id}/edit/delete_image/{catgalleryid}','Admin\CategoryController@delete_image');

Route::resource('/adminclasses','Admin\ClassesController');
Route::get('/adminclasses/{id}/edit/delete_image/{pcgalleryid}','CategoryController@delete_image'); 
Route::resource('/adminorganiser','Admin\OrganiserController');
Route::resource('/adminaddons','Admin\AddonsController');
Route::resource('/adminvolunteers', 'Admin\VolunteersController');
Route::resource('/admineventbookings','Admin\EventbookingsController');
Route::resource('/ticket','Admin\TicketsController');
Route::resource('/adminclassbooking','Admin\ClassbookingController');
Route::resource('/orders','Admin\OrdersController');
Route::post('image/upload/store','UserbookingController@fileStore');
Route::get('/photographersession/{id}/index/pc_delete/{pgalleryid}','UserbookingController@pc_delete');
Route::get('/loadmore','UserbookingController@loadDataAjax');
Route::get('/notification/{id}','UserbookingController@notification');
Route::get('/notitysec', 'UserbookingController@updatenoti');
Route::get('/feedback/{id}','UserbookingController@feedback');
Route::get('/photogharnotify', 'UserbookingController@updatephotonotify');
Route::get('subscribe', 'NewsletterController@subscribe');
Route::post('classfeedback', 'UserbookingController@classfeedback');
Route::get('/usernotiy', 'UserbookingController@adminupdatenotiy');
Route::get('ticket/create/{id}', 'Admin\TicketsController@create')->name('ticket.create');
Route::get('ticket/edit/{id}', 'Admin\TicketsController@edit')->name('ticket.edit');
Route::get('ticket/index/{id}', 'Admin\TicketsController@index')->name('ticket.index');
Route::get('/organiserregistration', 'OrganiserregistrationController@index')->name('organiserregistration');
Route::post('/organiserregistration/insert', 'OrganiserregistrationController@insert');
Route::get('/customersregistration', 'CustomersregistrationController@index')->name('customersregistration');
Route::post('/customersregistration/insert', 'CustomersregistrationController@insert');
Route::resource('/organiserdashboard', 'Organiser\ProfileController');
Route::resource('/eventbookings','Admin\EventbookingsController');
Route::get('event-listings', 'EventListingController@index');
Route::post('event-listings', 'EventListingController@index');
Route::get('event-details/{eventName}', 'EventListingController@getEventDetails')->name('event-details.getEventDetails');
Route::get('/requestdata', 'UserbookingController@requestdata');
Route::get('/sendmail', 'Admin\PosteventController@sendmail');
Route::get('customerdata/index/{id}', 'Admin\CustomerdataController@index')->name('customerdata.index');
Route::get('exportorders', 'Admin\OrdersController@exportorders');
Route::get('exportcustomer/{id}', 'Admin\CustomerdataController@exportcustomer');
Route::get('cancelorder/{id}', 'Admin\OrdersController@cancelorder');
Route::resource('contact', 'ContactController');
Route::get('/onboard-prereq','OrganiserregistrationController@organiserOnBoarding')->name('onboard-prereq.organiserOnBoarding');
Route::get('/OnBoardingRedirect','OrganiserregistrationController@OnBoardingRedirect');

/************************ start discount************************/
Route::resource('/discounts','Admin\DiscountsController');
Route::get('discounts/index/{id}', 'Admin\DiscountsController@index')->name('discounts.index');
Route::get('discounts/create/{id}', 'Admin\DiscountsController@create')->name('discounts.create');
Route::get('/discountsticket/{id}', 'Admin\DiscountsController@discountsticket')->name('discountsticket');
Route::get('/earlybirddiscounts/{id}', 'Admin\DiscountsController@earlybirddiscounts')->name('earlybirddiscounts');
Route::get('/bundleofferdiscounts/{id}', 'Admin\DiscountsController@bundleofferdiscounts')->name('bundleofferdiscounts');
Route::get('/ticketxdiscounts/{id}', 'Admin\DiscountsController@ticketxdiscounts')->name('ticketxdiscounts');
Route::get('/discountsticketedit/{id}', 'Admin\DiscountsController@discountsticketedit')->name('discountsticketedit');
Route::get('/earlybirddiscountsedit/{id}', 'Admin\DiscountsController@earlybirddiscountsedit')->name('earlybirddiscountsedit');
Route::get('/bundleofferdiscountsedit/{id}', 'Admin\DiscountsController@bundleofferdiscountsedit')->name('bundleofferdiscountsedit');
Route::get('/ticketxdiscountsedit/{id}', 'Admin\DiscountsController@ticketxdiscountsedit')->name('ticketxdiscountsedit');

/************************ end discount************************/
/************************ start ticket discount************************/
Route::resource('/ticketcollabration','Admin\TicketcollabrationController');
Route::get('/collabration/{id}', 'Admin\TicketcollabrationController@collabration')->name('collabration');
Route::get('/selfevents', 'Admin\TicketcollabrationController@selfevents')->name('selfevents');
Route::get('/collabration_org/{id}', 'Admin\TicketcollabrationController@collabration_org')->name('collabration_org'); 
Route::get('/collabrationevent', 'Admin\TicketcollabrationController@collabrationevent')->name('collabrationevent');
Route::get('/selfeventsedit/{id}', 'Admin\TicketcollabrationController@selfeventsedit')->name('selfeventsedit');
Route::get('/earlybirdedit/{id}', 'Admin\TicketcollabrationController@earlybirdedit')->name('earlybirdedit');
Route::get('/destroyticketcoll/{id}', 'Admin\TicketcollabrationController@destroyticketcoll')->name('destroyticketcoll');
Route::get('/destroyticket/{id}', 'Admin\TicketsController@destroyticket')->name('destroyticket');
Route::get('/destroydiscount/{id}', 'Admin\DiscountsController@destroydiscount')->name('destroydiscount');

Route::get('/cart', 'CartingController@index');
Route::resource('/cart', 'CartingController');
Route::get('/addtocart', 'CartingController@addtocart');
Route::get('/minCart', 'CartingController@minCart');
Route::get('/orderdetails/{orderid}', 'OrdersController@orderdetails');

Route::group(['middleware' => 'auth'], function () {
    Route::get('checkout','CheckoutController@shipping')->name('checkout.shipping');
    Route::resource('review','ProductReviewController');
});
Route::get('payment','CheckoutController@payment')->name('checkout.payment');
Route::post('store-payment','CheckoutController@storePayment')->name('payment.store');
Route::get('checkout','CheckoutController@shipping');
Route::post('/shippingstore/{id}', 'CheckoutController@shippingstore')->name('shippingstore');
Route::get('/updateorder', 'CartingController@updateorder');
Route::get('/ajaxdiscount', 'CartingController@ajaxdiscount');
Route::get('/destroy/{id}', 'Admin\CustomersController@destroy')->name('destroy');
Route::get('/destroyorganiser/{id}', 'Admin\OrganiserController@destroyorganiser')->name('destroyorganiser');
Route::get('/destroyevent/{id}', 'Admin\EventbookingsController@destroyevent')->name('destroyevent');
Route::get('/destroycontact/{id}', 'Admin\ContactusController@destroycontact')->name('destroycontact');
Route::get('addmoney/stripe', array('as' => 'addmoney.paywithstripe','uses' => 'AddMoneyController@payWithStripe'));
Route::post('addmoney/stripe', array('as' => 'addmoney.stripe','uses' => 'AddMoneyController@postPaymentWithStripe'));
Route::post('/charge', 'NewCheckoutController@charge');
Route::post('addmoney/stripe', 'AddMoneyController@postPaymentWithStripe');
Route::get('/paynow', 'Admin\PosteventController@paynow')->name('paynow');
Route::post('/chargeorg', 'Admin\PosteventController@chargeorg');

/************************ Start Deals************************/
Route::get('/featured-events', 'DealsController@index');

/************************ end Deals************************/
Route::get('/ticket-deals', 'TicketdealsController@index');
Route::get('/addtocartticket', 'CartingController@addtocartticket');
Route::get('/press-enquiries', 'EnquiryController@index')->name('index');
Route::resource('/adminmarketingmaterial','Admin\MarketingController');
Route::get('/sendmailpetal', 'Admin\EventbookingsController@sendmailpetal')->name('sendmailpetal');
Route::resource('/adminpayment', 'Admin\MailController');
Route::POST('/authPayment/{id}', 'Admin\MailController@authPayment')->name('authPayment');


Route::resource('/faq','Organiser\FaqController');
Route::get('/applypromo', 'CartingController@applypromo');

Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);

Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);

app/Http/Controllers/index.blade.php
@extends('layouts.default')
@section('content')
<!--content-section-start-->
<main>
 <section class="innercontentpart">
  
<div class="innercontent_text">
       <div class="container">
      <h1>Real Clients Photo Album</h1>
        <div class="row">
          

          <?php if(count($eventbookings) > 0) { ?>
          

          <div class="col-sm-12 classblks_div">
            

            <?php 
            $eventcount = 1;
            foreach($eventbookings as $event){ 
              if($eventcount%3=='1'){
                echo '<div class="col-sm-12">';
              }
              ?>
           
            <?php $id= $event->id;
         $eventbookings = DB::table('eventbookings')
                ->where('id','=', $id)
                ->where('deleted', 0)
                ->first();
         $assignid= $eventbookings->photographer_id;
         $userinfo = DB::table('users')
                ->where('id','=', $assignid)
                ->where('deleted', 0)
                ->first();
                ?>            

        <div class="col-sm-4 classblk">
              <a href="{{ route('community.show',$event->id) }}">
              <div class="classblk_bg">

               <img src="{{ url('/public') }}/images/corporateevent.png" class="img-responsive">
              
              <div class="class_content">
                <div class="row">
                <div class="col-sm-6">
            <span class="postdate">{{ date('F d, Y', strtotime($event->created_at)) }}</span>
            </div>
             <div class="col-sm-6 hearticon text-right">
              <?php
                                if($event->occassions!='') {
                                     $catnameArray = array(); 
                                     $ocsioncatArr = explode(',', $event->occassions);
                                    foreach($ocsioncatArr as $ocsioncatid) {
                                      $catNames = DB::table('categories')->where('id', '=', $ocsioncatid)->get();
                                      foreach($catNames as $ctName) {
                                          $catnameArray[] = $ctName->cat_name;
                                         }
                                      }
                                       echo implode(', ', $catnameArray);  
                                      }
                                     ?>   
              
            </div>
          </div>
              <p>{{$userinfo->first_name}} </p>
             
                <p>{!! \Illuminate\Support\Str::words($event->additional_notes, 20,'')  !!}</p>
              
              <div class="row">
                <div class="col-sm-8">
             <p class="class_reviewstars"><i class="fa fa-star"></i>
              <i class="fa fa-star"></i><i class="fa fa-star"></i>
              <i class="fa fa-star"></i><i class="fa fa-star"></i></p>
            </div>
            <div class="col-sm-4 hearticon text-right"><i class="fa fa-heart"></i>
              
            </div>
          </div>
            </div>
          </div>
          </a>
            </div>
<?php 
            if($eventcount%3=='0'){
                echo '</div>';
              }
              $eventcount++;
              } 

              ?>
</div>
<?php } ?>
</div>
</div>
        <div class="photoidea_sec greybg">
          <div class="container">
            <a href="{{ route('community.blogshow',$posts->id) }}">
             <h1>Photography Idea</h1>
             <div class="col-sm-6 photoidea_leftsec">
                  <?php 
                     $query = DB::table('posts');
                     $query->where('deleted', 0);
                     $query->where('status', 1);
                     $query->orderBy('id','DESC');
                     $query->limit(1);
                     $querys = $query->get(); ?>

           @foreach($querys as $query)
             @if($query->feature_images!='')
              <img src="{{ url('public') }}/uploads/post/feature_post/{{ $query->feature_images }}" class="img-responsive">
              @else
              <img src="{{url('/public')}}/images/dummy.jpg" class="img-responsive">
              @endif

              <div class="photoidea_content">
                <h3>Best Places in Paris To Get The Best View of Eiffel Tower!</h3>
                <p>{{str_limit($query->description, 100)}}</p>
                <p class="postdates">
                  <span>BY: Admin</span>
                  <span>{{ date('F d, Y', strtotime($query->created_at)) }}</span>
                </p>
              </div>
              @endforeach
         
        </div>
                  <div class="col-sm-6 photoidea_rightsec">

                    <div class="row">
              @foreach($posts AS $post)
               <div class="col-sm-6 photosmall_sec">
                   @if($post->feature_images!='')
                  <img src="{{ url('public') }}/uploads/post/feature_post/{{ $post->feature_images }}" class="img-responsive">
                  @else
                  <img src="{{url('/public')}}/images/dummy.jpg" class="img-responsive">
                  @endif
                  <div class="photoidea_content">
                       <h3>Best Places in Paris To Get The Best 
                        View of Eiffel Tower!</h3>
                        <p class="postdates"> <span>{{ date('F d, Y', strtotime($post->created_at)) }}</span> </p>
                   </div>
                </div>
              @endforeach
              </div>

        </div>
        <div class="seemore_btn text-center">
          <a href="#">Read More</a>
        </div>
      <!--  -->
      


          </a>
      </div>
          </div

          <div class="society_sec">
              <div class="society_content">
                <h1>Help This Society</h1>
                <a href="{{ url('/volunteer-session') }}">
                <div class="society_imgsec">
                  <h1>Volunteer <br/> Photographar</h1>
                </div>
              </a>
            </div>
        </div>
 </section>
</main>
<!--content-section-end-->
@endsection

resources/views/Cart/index.blade.php
<?php use \App\Http\Controllers\CartingController;?>
@extends('layouts.innerdefault')
@section('content')
   <?php
   $subtotal_amount=0;
   $discount_given=0;
   $discounted_amount=0;
   $totalbookingfee=0;
 
   ?>
  <!-- CONTACT SECTION -->
<section class="section-checkout">
   
<div class="container">
  <!-- row -->
  @if(count($_discountobjlist)>0)
@foreach($eventIdList as $Items)
<!-- row -->
<?php

$thisEventItems=CartingController::get_array_details_front($Items,$_discountobjlist,'event_id');
$EventSubTotal=0;
 ?>
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive pricing-table">
        <table class="table table-bordered table-hover">
         <thead>
            <tr>
              <?php
              $eventname=DB::table('eventbookings')->select('event_title')->where('id','=',$Items)->first();

              ?>
               <th colspan="5" class="e-name">{{$eventname->event_title}}</th>
            </tr>
            <tr>
              <th>Ticket Type</th>
              <th>Net Price</th>
              <th>Quantity</th>
              <th>Total</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @if(count($thisEventItems)>0)
              @foreach($thisEventItems as $cartItems)
              
              <tr>
              <td>{{$cartItems->TicketTitle}} </td>
              <td><i class="fa fa-gbp"></i> <!-- {{$cartItems->subtotal_amount}} -->
                 <?php
              $ticket_type=$cartItems->TicketTitle;
              $ticketid=DB::table('tickets')->select('prices')->where('ticket_type','=',$ticket_type)->first();
              ?>
               {{$ticketid->prices}}

              </td>
              <td>  {!! Form::open(['route' => ['cart.update',$cartItems->rowId], 'method' => 'PUT']) !!}
                        <input name="qty" type="number" class="form-control cartupdate" value="{{$cartItems->Quantity}}">
                        <input type="hidden" id="size" value="{{$cartItems->event_id}}">
                        {!! Form::close() !!}</td>
              <td><i class="fa fa-gbp"></i> {{$cartItems->discounted_amount}}</td>
              <th>
                <form action="{{route('cart.destroy',$cartItems->rowId)}}"  method="POST">
                           {{csrf_field()}}
                           {{method_field('DELETE')}}
                           <button class="btn btn-primary" type="submit"><i class="fa fa-trash"></i></button>
                         </form>
              </th>
              <?php
              $EventSubTotal=$EventSubTotal+$cartItems->discounted_amount;
              $subtotal_amount=$subtotal_amount+$cartItems->subtotal_amount;
              $discount_given=$discount_given+$cartItems->discount_given;
              $totalbookingfee=$totalbookingfee+$cartItems->booking_fee;
              $discounted_amount=$discounted_amount+$cartItems->discounted_amount;
              

              ?>
              </tr>
              @endforeach
              @endif
              
            
            
          </tbody>
          <tfoot>
            <tr>
              <th colspan="5" class="total-amt">Sub-total: <i class="fa fa-gbp"></i>{{$EventSubTotal}}</th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
  <!--// row -->

@endforeach
@endif
  
 </div>
  <div class="container">
      <div class="row row-promo">
    <div class="col-md-12 col-xs-12">
   <div class="card">
          <h4 class="sub-heading">Apply Promo Codes</h4>
      <div class="card-body">
       @include('layouts.flash-message')
      <form id="contact-form" class="settingform" action="{{ url('/applypromo') }}" method="GET" enctype="multipart/form-data">
       {{ csrf_field() }}  
  
      <div class="input-group">
      <input type="text" class="form-control" aria-label="..." name="couponCode" required="">

@if(count($_discountobjlist)>0)
@foreach($eventIdList as $Items)
<!-- row -->
<?php
$thisEventItems=CartingController::get_array_details_front($Items,$_discountobjlist,'event_id');
 ?>
       @if(count($thisEventItems)>0)
              @foreach($thisEventItems as $cartItems)
            <?php 
              $ticket_type=$cartItems->TicketTitle;
              $ticketid=DB::table('tickets')->where('ticket_type','=',$ticket_type)->first();
            ?>
      <input type="hidden" class="form-control" aria-label="..." name="ticket_type_id" value="{{$ticketid->id}}" required="">
       @endforeach
        @endif

@endforeach
@endif
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default">Apply</button>
      </div><!-- /btn-group -->
      </div><!-- /input-group -->
      
      </form>
          </div>
        </div>
      </div>
    </div>

   <!--// row -->
        <!-- row -->
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive pricing-table">
        <table class="table table-bordered table-hover">
          <tbody>
            <tr>
               <th class="e-name text-left">Total Amount To Be Paid</th>
              <th  class="total-amt text-right"> 
                        <p>SubTotal: <i class="fa fa-gbp"></i> {{$subtotal_amount}}</p>
                        <p>Discount Given:<i class="fa fa-gbp"></i> {{$discount_given}}</p>
                        <p>Booking Fee: <i class="fa fa-gbp"></i>{{$totalbookingfee}}</p>
                        <p>Total: <i class="fa fa-gbp"></i>{{$discounted_amount+$totalbookingfee}}</p>
                    
                    </th>
            </tr>
          </tbody>
        </table>
      </div><!--end of .table-responsive-->
     <?php   $user_id = Auth::user()->id ;
     $user_email=Auth::user()->email;

     ?>

        <form action="{{url('/charge')}}" method="POST">
            {{ csrf_field() }}
            <?php $key=DB::table('business_settings')->first();
                  $test=$key->stripe_mode;
                  $test_publish_key=$key->test_publish_key;
                  $live=$key->stripe_mode;
                  $live_publish_key=$key->live_publish_key;
                    
           

             if($test=='Test'){ ?>
                                  <script
                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="{{$test_publish_key}}"
                    data-amount="{{($discounted_amount+$totalbookingfee)*100}}"
                    data-name=""
                    data-description=""
                    data-image=""
                    data-email={{$user_email}}
                    data-locale="auto"
                    data-currency="gbp">
                     </script>
                 <?php } 

                  else { ?>
                      <script
                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="{{$live_publish_key}}"
                    data-amount="{{($discounted_amount+$totalbookingfee)*100}}"
                    data-name=""
                    data-description=""
                    data-image=""
                    data-email={{$user_email}}
                    data-locale="auto"
                    data-currency="gbp">
                      </script>
                 <?php } ?>

              <input type="hidden" name="data_amount" value="{{($discounted_amount+$totalbookingfee)*100}}">
              <input type="hidden" name="user_id" value="{{$user_id}}">
              <input type="hidden" name="totalbookingfee" value="{{$totalbookingfee}}">
              <input type="hidden" name="discount_given" value="{{$discount_given}}">
        </form>
     <!--  <div class="col-pay-now">
          <a href="#" id="updateorder" updateorder="" class="btn btn-primary"> Pay Now! </a>
      </div> -->
    </div>
  </div>
   <!--// row -->
</div>


</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
   
   $(".cartupdate").change(function() {
     this.form.submit();
});
 });
</script>

@endsection

resources/views/Cart/minCart.blade.php
<?php use \App\Http\Controllers\CartingController;?>
<li class="c_head"><label>My cart</label></li>
 <li class="item-list item-head">
                <div class="item-name">
                <label>Ticket / Event</label>
             
                </div>
                 <div class="item-quantity">
                   <label>Quantity</label>
                 </div>
                 <div class="item-price">
                   <label>Price</label>
                   
                   </div>
                   <div class="item-action">
                   <label>Action</label>
                   </div>
                  </li>
                  
                  <?php 
                  $EventSubTotal=0;?>

                  @foreach($_discountobjlist as $cartItem)         

              <!--  //item-list -->
          <li class="item-list ">
                <div class="item-name">
                
<!--   <span class="e-media"><img src="images/e2.jpg"></span>-->             
    <span class="t-type">
                  <span class="t-name">{{$cartItem->TicketTitle." tickets for ".$cartItem->Event_Name->event_title}}</span>
                </span>
                </div>
                 <div class="item-quantity">
                  
                   <span class="t-qty">
                    <div class="input-group">
              <span class="form-control input-number" >{{$cartItem->Quantity}}</span>

              </div>
               </span>
                </div>
                 <div class="item-price">
                 
                   <span class="t-price"><i class="fa fa-gbp"></i>{{$cartItem->subtotal_amount}}</span>
                   </div>
                     <div class="item-action">
                 
                 
                    <form action="{{route('cart.destroy',$cartItem->rowId)}}"  method="POST">
                           {{csrf_field()}}
                           {{method_field('DELETE')}}
                            <button class="btn btn-primary" type="submit" value="Delete"><i class="fa fa-trash-o"></i></button>
                         </form>
                     
                   </div>
                  </li>
              <?php
              $EventSubTotal=$EventSubTotal+$cartItem->subtotal_amount;
            

              ?>
              <!--  //item-list -->
              @endforeach
                   <!--  item-list -->
              <li class="item-list">
                <span class="total-price">
                  Total Price: <i class="fa fa-gbp"></i> {{$EventSubTotal}}


                  </span>
              </li>
                  <!--  //item-list -->
                   <!--  item-list -->
                 <li class="item-checkout">
               <a href="{{url('/cart')}}" class="btn btn-primary">
                CHECKOUT
               </a>
                </li>
                 <!--  //item-list -->