routes/web.php
Route::get('auth/google', 'Auth\LoginController@redirectTOGoogle');
Route::get('googlecallback', 'Auth\LoginController@Googlecallback');
Route::resource('/learn', 'LearnController');
Route::resource('/blog', 'BlogController');
Route::resource('/community', 'CommunityController');
Route::resource('/blog', 'BlogController');
Route::resource('/about', 'AboutController');
Route::resource('/occasions', 'OccasionsController');
Route::get('classpaypalpayment', 'BookingController@classpaypalpayment');
Route::post('classstripepayment', 'BookingController@classstripepayment');
Route::POST('/userdiscountpayment', 'UserbookingController@discountpayment');
Route::get('userclasspaypalpayment', 'UserbookingController@classpaypalpayment');
Route::post('userclassstripepayment', 'UserbookingController@classstripepayment');
Route::get('usereventpaypalpayment', 'UserbookingController@paypalpayment');
Route::post('usereventstripepayment', 'UserbookingController@stripepayment');
Route::resource('/customerdashboard', 'Customer\ProfileController');
Route::resource('/customerevents', 'Customer\EventController');
Route::resource('/customerpayments', 'Customer\PaymentController');
Route::resource('/customerclasses', 'Customer\ClassesController');
Route::resource('/customerfeedback','Customer\FeedbackController');
Route::get('login',array('as'=>'login',function(){
    return view('auth.login');
}));



Route::resource('/photographerdashboard', 'Photographer\ProfileController');
Route::resource('/photographersession', 'Photographer\SessionController');
Route::resource('/photographerclasses', 'Photographer\ClassesController');
Route::resource('/photgrapherfeedback','Photographer\FeedbackController');
Route::resource('/photographerpayments', 'Photographer\PaymentController');
Route::resource('/photographergallery', 'Photographer\GalleryController');

Route::get('/photographergallery/{id}/index/delete_image/{pcgalleryid}','Photographer\GalleryController@delete_image');

Route::resource('/admindashboard', 'Admin\DashboardController');
// Route::resource('/adminfaq', 'Admin\FaqController');
Route::resource('/adminprofiles', 'Admin\ProfilesController');
Route::resource('/adminbusinesssetting', 'Admin\BusinesssettingController');
Route::resource('/admincategory','Admin\CategoryController');
Route::resource('/adminposts', 'Admin\PostsController');
Route::resource('/adminaboutus', 'Admin\AboutusController');
Route::resource('/admincontactus', 'Admin\ContactusController');
Route::resource('/adminhowitworks', 'Admin\HowitworksController');
Route::resource('/adminhomephotographers', 'Admin\HomephotographersController');
Route::resource('/adminhomecomingsoons', 'Admin\HomecomingsoonsController');
Route::resource('/postsevent', 'Admin\PosteventController');

Route::resource('/admincontacts', 'Admin\ContactsController');
// Route::get('/adminposts', 'PostsController@co_destroy')
Route::resource('/admincustomer', 'Admin\CustomersController');
Route::resource('/admincustomers', 'Admin\CustomerRegisterController');
Route::resource('/admincategory','Admin\CategoryController');
Route::get('/admincategory/{id}/edit/delete_image/{catgalleryid}','Admin\CategoryController@delete_image');

Route::resource('/adminclasses','Admin\ClassesController');
Route::get('/adminclasses/{id}/edit/delete_image/{pcgalleryid}','CategoryController@delete_image'); 
Route::resource('/adminorganiser','Admin\OrganiserController');
Route::resource('/adminaddons','Admin\AddonsController');
Route::resource('/adminvolunteers', 'Admin\VolunteersController');
Route::resource('/admineventbookings','Admin\EventbookingsController');
Route::resource('/ticket','Admin\TicketsController');
Route::resource('/adminclassbooking','Admin\ClassbookingController');
Route::resource('/orders','Admin\OrdersController');
Route::post('image/upload/store','UserbookingController@fileStore');
Route::get('/photographersession/{id}/index/pc_delete/{pgalleryid}','UserbookingController@pc_delete');
Route::get('/loadmore','UserbookingController@loadDataAjax');
Route::get('/notification/{id}','UserbookingController@notification');
Route::get('/notitysec', 'UserbookingController@updatenoti');
Route::get('/feedback/{id}','UserbookingController@feedback');
Route::get('/photogharnotify', 'UserbookingController@updatephotonotify');
Route::get('subscribe', 'NewsletterController@subscribe');
Route::post('classfeedback', 'UserbookingController@classfeedback');
Route::get('/usernotiy', 'UserbookingController@adminupdatenotiy');
Route::get('ticket/create/{id}', 'Admin\TicketsController@create')->name('ticket.create');
Route::get('ticket/edit/{id}', 'Admin\TicketsController@edit')->name('ticket.edit');
Route::get('ticket/index/{id}', 'Admin\TicketsController@index')->name('ticket.index');
Route::get('/organiserregistration', 'OrganiserregistrationController@index')->name('organiserregistration');
Route::post('/organiserregistration/insert', 'OrganiserregistrationController@insert');
Route::get('/customersregistration', 'CustomersregistrationController@index')->name('customersregistration');
Route::post('/customersregistration/insert', 'CustomersregistrationController@insert');
Route::resource('/organiserdashboard', 'Organiser\ProfileController');
Route::resource('/eventbookings','Admin\EventbookingsController');
Route::get('event-listings', 'EventListingController@index');
Route::post('event-listings', 'EventListingController@index');
Route::get('event-details/{eventName}', 'EventListingController@getEventDetails')->name('event-details.getEventDetails');
Route::get('/requestdata', 'UserbookingController@requestdata');
Route::get('/sendmail', 'Admin\PosteventController@sendmail');
Route::get('customerdata/index/{id}', 'Admin\CustomerdataController@index')->name('customerdata.index');
Route::get('exportorders', 'Admin\OrdersController@exportorders');
Route::get('exportcustomer/{id}', 'Admin\CustomerdataController@exportcustomer');
Route::get('cancelorder/{id}', 'Admin\OrdersController@cancelorder');
Route::resource('contact', 'ContactController');
Route::get('/onboard-prereq','OrganiserregistrationController@organiserOnBoarding')->name('onboard-prereq.organiserOnBoarding');
Route::get('/OnBoardingRedirect','OrganiserregistrationController@OnBoardingRedirect');

/************************ start discount************************/
Route::resource('/discounts','Admin\DiscountsController');
Route::get('discounts/index/{id}', 'Admin\DiscountsController@index')->name('discounts.index');
Route::get('discounts/create/{id}', 'Admin\DiscountsController@create')->name('discounts.create');
Route::get('/discountsticket/{id}', 'Admin\DiscountsController@discountsticket')->name('discountsticket');
Route::get('/earlybirddiscounts/{id}', 'Admin\DiscountsController@earlybirddiscounts')->name('earlybirddiscounts');
Route::get('/bundleofferdiscounts/{id}', 'Admin\DiscountsController@bundleofferdiscounts')->name('bundleofferdiscounts');
Route::get('/ticketxdiscounts/{id}', 'Admin\DiscountsController@ticketxdiscounts')->name('ticketxdiscounts');
Route::get('/discountsticketedit/{id}', 'Admin\DiscountsController@discountsticketedit')->name('discountsticketedit');
Route::get('/earlybirddiscountsedit/{id}', 'Admin\DiscountsController@earlybirddiscountsedit')->name('earlybirddiscountsedit');
Route::get('/bundleofferdiscountsedit/{id}', 'Admin\DiscountsController@bundleofferdiscountsedit')->name('bundleofferdiscountsedit');
Route::get('/ticketxdiscountsedit/{id}', 'Admin\DiscountsController@ticketxdiscountsedit')->name('ticketxdiscountsedit');

/************************ end discount************************/
/************************ start ticket discount************************/
Route::resource('/ticketcollabration','Admin\TicketcollabrationController');
Route::get('/collabration/{id}', 'Admin\TicketcollabrationController@collabration')->name('collabration');
Route::get('/selfevents', 'Admin\TicketcollabrationController@selfevents')->name('selfevents');
Route::get('/collabration_org/{id}', 'Admin\TicketcollabrationController@collabration_org')->name('collabration_org'); 
Route::get('/collabrationevent', 'Admin\TicketcollabrationController@collabrationevent')->name('collabrationevent');
Route::get('/selfeventsedit/{id}', 'Admin\TicketcollabrationController@selfeventsedit')->name('selfeventsedit');
Route::get('/earlybirdedit/{id}', 'Admin\TicketcollabrationController@earlybirdedit')->name('earlybirdedit');
Route::get('/destroyticketcoll/{id}', 'Admin\TicketcollabrationController@destroyticketcoll')->name('destroyticketcoll');
Route::get('/destroyticket/{id}', 'Admin\TicketsController@destroyticket')->name('destroyticket');
Route::get('/destroydiscount/{id}', 'Admin\DiscountsController@destroydiscount')->name('destroydiscount');

Route::get('/cart', 'CartingController@index');
Route::resource('/cart', 'CartingController');
Route::get('/addtocart', 'CartingController@addtocart');
Route::get('/minCart', 'CartingController@minCart');
Route::get('/orderdetails/{orderid}', 'OrdersController@orderdetails');

Route::group(['middleware' => 'auth'], function () {
    Route::get('checkout','CheckoutController@shipping')->name('checkout.shipping');
    Route::resource('review','ProductReviewController');
});
Route::get('payment','CheckoutController@payment')->name('checkout.payment');
Route::post('store-payment','CheckoutController@storePayment')->name('payment.store');
Route::get('checkout','CheckoutController@shipping');
Route::post('/shippingstore/{id}', 'CheckoutController@shippingstore')->name('shippingstore');
Route::get('/updateorder', 'CartingController@updateorder');
Route::get('/ajaxdiscount', 'CartingController@ajaxdiscount');
Route::get('/destroy/{id}', 'Admin\CustomersController@destroy')->name('destroy');
Route::get('/destroyorganiser/{id}', 'Admin\OrganiserController@destroyorganiser')->name('destroyorganiser');
Route::get('/destroyevent/{id}', 'Admin\EventbookingsController@destroyevent')->name('destroyevent');

app/Http/Controllers/Organiser/CommunityController.php
<?php
namespace App\Http\Controllers;
use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;
use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Auth;
use App\Eventbookings;
use Session;
use DB;
use Hash;
use Image;
use App\Classes\ErrorsClass;
use App\Classes\CalendarClass;

class CommunityController extends Controller
{    

    public function __construct()
    {

    }

      public function index(Request $request $id)
    {
       // $userid = Auth::user()->id;
       // $id = User::findOrFail($userid); 

      $eventbookings = DB::table('eventbookings')
                               ->where('deleted', 0)
                               ->orderBy('id','DESC')
                               ->paginate(6);
        

             $categories = DB::table('categories')
              ->where('status', '=', 1)
             ->where('deleted', '=', 0)
             ->get();

             $galleryevent = DB::table('eventgallery')
                           ->where('id','=', $eventbookings->user_id)
                             ->where('eventid','=', $id)
                             ->where('status', '=', 1)
                             ->where('deleted', '=', 0)
                             ->orderBy('id','DESC')
                             ->get();         

       return view('community.index',compact('eventbookings', 'categories','galleryevent'));
    }
    
     public function clientalbum(Request $request)
    {

       return view('community.client-album');
    }
   
    public function clientview(Request $request)
    {

       return view('community.client-single');
    }

    public function volunteersession(Request $request)
    {

       return view('community.volunteer-session');
    }

    public function show($id)
    {   
         $event = DB::table('eventbookings')
                            ->where('id','=', $id)
                            ->where('status', '=', 1)
                            ->where('deleted', '=', 0)
                            ->first(); 

        $userinfo = DB::table('users')
                            // ->where('id','=', $class->user_id)
                            ->where('status', '=', 1)
                            ->where('deleted', '=', 0)
                            ->first();
          $categories = DB::table('categories')
              ->where('status', '=', 1)
             ->where('deleted', '=', 0)
             ->first();                 

       
        $eventgalleryimages = DB::table('eventgallery')
                             ->where('eventid','=',$event->user_id)
                             ->where('status', '=', 1)
                             ->where('deleted', '=', 0)
                             ->orderBy('id','DESC')
                             ->first();   
                  
        // $BusinessInfo = DB::table('business_settings')->where('status', '1')->first(); 
                    
        return view('community.show',compact('event','userinfo','categories','$eventgalleryimages'));
    }

    
}

app/Http/Controllers/Organiser/FaqController.php
<?php

namespace App\Http\Controllers\Organiser;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Auth;
use App\Eventbookings;
use Session;
use DB;
use Hash;
use Image;
use App\Classes\ErrorsClass;
use App\Classes\CalendarClass;

class FaqController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

     public function index(Request $request)
    {
    	

      return view('Organiser.FAQ.index');
    }

//     public function getDownload($filename)
//     {
//     // Define the path and the extension
//     $file = public_path() . '/uploads/'. $filename;
//     $ext = pathinfo($filename, PATHINFO_EXTENSION);

//     if($ext == 'png' || 'PNG'){
//       $headers = array(
//           'Content-Type' => 'image/png',
//         );
//     }

//     else if($ext == 'jpg' || 'jpeg' || 'JPEG' || 'JPG'){
//       $headers = array(
//           'Content-Type' => 'image/jpeg',
//         );
//       }

//       return response()->download($file, $filename, $headers);
// }
}

app/Http/Controllers/Organiser/FeedbackController.php
<?php

namespace App\Http\Controllers\Photographer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Pagination\Paginator;
use App\User;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Auth;
use App\Eventbookings;
use Session;
use DB;
use Hash;
use Image;
use App\Classes\ErrorsClass;
use App\Classes\CalendarClass;

class FeedbackController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index(Request $request){
         
        try {

        $id = Auth::user()->id;
        $customer = User::findOrFail($id); 
        $page = $request->input('page');
        $type = $request->type;

               if($request->perpage!=''){
                    $perpage = $request->perpage;
               } else {
                    $perpage = '1';
               } 

             $query = DB::table('eventbookings');
             $query->where('booking_status', '=', 1);
             $query->where('payment_status', '=', 1);
             $query->where('status', '=', 1);;
             $query->where('deleted', '=', 0);
             $query->where('photographer_id', '=', $id);
             if($type=='complete'){
             $query->where('start_date', '<', date('Y-m-d'));
             } else {
             $query->where('start_date', '>', date('Y-m-d'));
             }
             $query->orderBy('id','DESC');
             $eventbookings = $query->paginate(10);

        $feedbacks= DB::table('feedback')
        		->where('pc_id', '=', $id)
        		->get();
                return view('Photographer.Feedback.index',compact('customer', 'eventbookings','page', 'type' , 'perpage','feedbacks'));

        } catch (\Illuminate\Database\QueryException $e) {

            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);

        } catch (\Exception $e) {
            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);
       }
        //return view('Photographer.session');
    }
 
}

resources/views/Admin/Organiser/index.blade.php
@extends('layouts.userdefault')
@section('content')
<!--booking-sec-start-->
  <!--booking-sec-start-->
<div class="dashboard_section">
  <div class="col-sm-2 col-xs-12 dashboard_left nopadding">
      @include('layouts.usersidebar')
  </div>
      <div class="col-sm-12 dashboard_right">
        @include('layouts.flash-message') 

        

         <div class="content">
        <div class="container-fluid">
        <!--   row -->
          <div class="row">
          
         <div class="col-sm-7 table-search searchbar">
        <form class="navbar-form navbar-right" name="searchfrm" id="searchfrm" method="GET" action="{{ route('adminorganiser.index') }}">
          <span class="bmd-form-group"><div class="input-group input-group-sm" "="">
             <input type="text" class="form-control" placeholder="Search here" name="search_input" id="s" value="">
             <div class="input-group-btn">
           <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
          </div>
        </div></span>
        </form>
    </div>


        <div class="col-sm-5 selectdiv topbar_selectiv text-right createbtn">
               <a class="btn btn-primary" href="{{ route('adminorganiser.create') }}"> Create New Organiser </a>
         </div>
      
  
      </div>

          <!-- //  row -->
              
              <div class="row">
            <div class="col-md-12">

                <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Organisers</h4>
                  <p class="card-category"> </p>
                </div>
      
             <div class="card-body">
                  <div class="table-responsive">
                  <table class="table">

                <thead class=" text-primary">

                    <tr >
                       <th  class="">Image</th>
                        <th class="">Name</th>
                        <th class="">Email</th>
                        <th class="">Phone</th>
                        <th class="">Registered</th>
                       
                        <th class="">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(count($organisers)>0)
                     @foreach ($organisers as $organiser)
                    <tr class="tabledata">

                      <td class="column2 user_img">
                        @if($organiser->profile_picture!='') 
                        <img src="{{ url('public') }}/uploads/profileimages/{{ $organiser->profile_picture }}" class="img-responsive" style="width: 40px; height: 30px;">
                         @else
                        <img src="{{ url('public') }}/images/avtar.jpg" style="width: 40px; height: 30px;">
                       @endif
                        
                      </td>
                        
                        <td class="">{{ $organiser->first_name }}</td>
                       
                        <td class="">{{ $organiser->email }}</td>
                       
                        <td class="">{{ $organiser->phone }}</td>
                       
                        <td class="">{{ \Carbon\Carbon::parse($organiser->created_at)->format('d M Y')}}</td>
                       
                       <!--  <td class="">
                          <?php
                          if($organiser->status==1) {
                            echo 'Active';
                          } else {
                            echo 'Inactive';
                          }
                          ?>
                        </td> -->


                        <td>
                        <div class="dropdown d-action">
                              <a class="btn-act" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                               
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="">

                    <label> Organiser </label>
                     <a class="dropdown-item" href="{{ route('adminorganiser.edit',$organiser->id) }}" title="Edit" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-edit"></i> Edit </a>
                     <a class="dropdown-item" href="{{ route('adminorganiser.show',$organiser->id) }}" title="Show" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-eye"></i> View </a>

                     <a class="dropdown-item">
                      <form name="request" id="request" class="request" method="GET" action="{{url('/')}}/destroyorganiser/{{$organiser->id}}">
                         <button type="submit" class="del_sec_mew"><i class="fa fa-trash"></i>Delete</button></form>
                       </a>

                        </div>
                      </div>
                    </td>
                       
                    </tr>
                     @endforeach
                     @else
                     <tr class="tablesection">
                        <td colspan="7" style="text-align: center;"><b>No record found</b></td>
                    </tr>
                    @endif

        </tbody>
      </table>
    </div>
     @if(count($organisers) > 0)
<div class="pagination_section">
   <div class="col-sm-3 selectdiv text-right">
    <form name="" id="page" method="get" action="{{ url('/adminorganiser') }}" >
    <label>Showing:</label>
    <select name="perpage" id="perpage" onchange="document.getElementById('page').submit();">
       <option value="10" @if($perpage=='10'){{'selected'}}@endif>10</option>
      <option value="20" @if($perpage=='20'){{'selected'}}@endif>20</option>
      <option value="50" @if($perpage=='50'){{'selected'}}@endif>50</option>
      <option value="100" @if($perpage=='100'){{'selected'}}@endif>100</option>
    </select>
    </form>
  </div>

<div class="col-sm-4 total_div">
 
</div>
<div class="col-sm-5 pagination_div">
<nav aria-label="Page navigation">

<!--   {!! $organisers->render() !!}
 --></nav>

  </div>
  
 
</div>
@endif
      
          <!--   <div class="dashboard_footer">
        <div class="col-sm-8 left_dashboardfooter">
          <ul>
            <li>Copyright <span>Mrs.Portrait.</span>All rights reserved</li>
            <li><a href="#">Careers</a></li>
            <li><a href="#">Privacy Policy</a></li>
          </ul>
        </div>
        <div class="col-sm-4 right_dashboardfooter text-right">
          <a href="#">Feedback</a>
        </div>
      </div> -->
      </div>


    </div>

    </div>
  </div>
</div>
</div>
</div>
</div>    

 <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.min.js"></script>

  <script type="text/javascript">

    $(document).ready(function () {        

        $('[data-toggle=confirmation]').confirmation({

            rootSelector: '[data-toggle=confirmation]',

            onConfirm: function (event, element) {

                element.closest('form').submit();

            }

        });   

    });

</script>
<style type="text/css">
  input#search_input {
    height: 32px !important;
</style>

@endsection

resources/views/Admin/Organiser/show.blade.php
@extends('layouts.userdefault')
@section('content')
@include('layouts.flash-message') 

 <div class="dashboard_section">
  <div class="col-sm-2 col-xs-12 dashboard_left nopadding">
       @include('layouts.usersidebar') 
  </div>

    <div class="container-fluid">
          <div class="row">
            <div class="col-md-12 col-xs-12">
    <div class="card">
            <div class="card-header card-header-primary">
              <p class="singalname">{{ $organiser->first_name }} {{ $organiser->last_name }}</p>
            </div>

            <div class="card-body">
        <form>
      <div class="row">
        <div class="col-md-12">
                         <div class="row">
                         <div class="col-md-6">
                           <p class="rightsidetext"><span class="lablname">Phone :</span> {{ $organiser->phone }} </p>
                         </div>
                           <div class="col-md-6">
                              <p class="rightsidetext"><span class="lablname">Email :</span>{{ $organiser->email }}</p>
                                </div>
                              </div>
            
                                       <div class="row">
                                       <div class="col-md-6">
                                        <p class="rightsidetext"><span class="lablname">Country :</span><?php $id=$organiser->country;
                                        $countries = DB::table('all_towns')->where('id','=',$id)->get();
                                        foreach ($countries as $value) {
                                        echo $value->town_name;                            
                                         }
                                       ?></p>
                                       </div>
                                       <!-- <div class="col-md-6">
                                        <p class="rightsidetext"><span class="lablname">Status :</span> <?php 
                                 if($organiser->status=='1') { 
                                    echo 'Active';
                                  } else {
                                    echo 'Inactive';
                                   }?></p>
                                 </div> -->
                               </div>
                               <div class="row">
                                <div class="col-md-6">
                                   @if (Auth::user()->profile_picture!='' && Auth::user()->profile_picture!='NULL')
                             <img src="{{ url('public') }}/uploads/profileimages/{{ $organiser->profile_picture }}" class="img-circle" style="width:200px">
                                   @else
                            <img src="{{ url('public') }}/images/avtar.jpg" class="img-circle">
                              @endif
                                </div>
                              </div>
                            </div>
            
    </div>
  </form>
</div>
</div>
</div>
</div>
</div>
</div>


<style>
  span.lablname {
    font-size: 14px;
    font-weight: bold;
}
.dasbagcol{
  background: #f7f9fc;
margin-top: 0px;
padding-top: 42px;
}
.sectionbox {
    background: #ffff;
    padding-top: 13px;
    padding-bottom: 13px;
}
p.singalname {
    font-size: 27px;
}
span.lablname {
    float: left;
    width: 40%;
}
.rightbox {
    border-left: solid 1px #d2d2d2;
}

span.labldata {
    color: #969da5;
}
p.singalemail {
    color: #969da5;
}
</style>

@endsection