routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});
/*Route::get('/terms-conditions', function () {
    return view('terms-conditions');
});*/
Route::get('/terms-conditions', 'TermsController@index')->name('index');
Route::get('/privacy-policy', 'PrivacyController@index')->name('index');
Route::get('/FAQs', 'FaqController@index')->name('index');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/occasions', 'HomeController@occasions')->name('occasions');
Auth::routes();

Route::post('/forgotpassword', 'BookingController@forgotpassword');
Route::get('/booking', 'BookingController@index');
Route::get('/payment/{id}', 'BookingController@payment');
Route::get('/usersignup/{id}', 'BookingController@usersignup');
Route::get('/calendardates', 'BookingController@calendardates');
Route::POST('/bookingdata', 'BookingController@bookingdata');
Route::POST('/storeeventdata', 'BookingController@storeeventdata');
Route::POST('/discountpayment', 'BookingController@discountpayment');
Route::POST('/stripepayment', 'BookingController@stripepayment');
Route::get('/paypalpayment', 'BookingController@paypalpayment');
Route::get('/checkuseremail', 'BookingController@checkuseremail');
Route::get('/checkedituseremail', 'BookingController@checkedituseremail');
Route::resource('/volunteerssession', 'VolunteerssessionController');
Route::get('/client-album', 'CommunityController@clientalbum');
Route::get('/client-view', 'CommunityController@clientview');


Route::get('auth/google', 'Auth\LoginController@redirectTOGoogle');
Route::get('googlecallback', 'Auth\LoginController@Googlecallback');
Route::resource('/learn', 'LearnController');
Route::resource('/blog', 'BlogController');
Route::resource('/community', 'CommunityController');
Route::resource('/blog', 'BlogController');
Route::resource('/about', 'AboutController');
Route::resource('/occasions', 'OccasionsController');
Route::get('classpaypalpayment', 'BookingController@classpaypalpayment');
Route::post('classstripepayment', 'BookingController@classstripepayment');
Route::POST('/userdiscountpayment', 'UserbookingController@discountpayment');
Route::get('userclasspaypalpayment', 'UserbookingController@classpaypalpayment');
Route::post('userclassstripepayment', 'UserbookingController@classstripepayment');
Route::get('usereventpaypalpayment', 'UserbookingController@paypalpayment');
Route::post('usereventstripepayment', 'UserbookingController@stripepayment');
Route::resource('/customerdashboard', 'Customer\ProfileController');
Route::resource('/customerevents', 'Customer\EventController');
Route::resource('/customerpayments', 'Customer\PaymentController');
Route::resource('/customerclasses', 'Customer\ClassesController');
Route::resource('/customerfeedback','Customer\FeedbackController');
Route::get('login',array('as'=>'login',function(){
    return view('auth.login');
}));



Route::resource('/photographerdashboard', 'Photographer\ProfileController');
Route::resource('/photographersession', 'Photographer\SessionController');
Route::resource('/photographerclasses', 'Photographer\ClassesController');
Route::resource('/photgrapherfeedback','Photographer\FeedbackController');
Route::resource('/photographerpayments', 'Photographer\PaymentController');
Route::resource('/photographergallery', 'Photographer\GalleryController');

Route::get('/photographergallery/{id}/index/delete_image/{pcgalleryid}','Photographer\GalleryController@delete_image');

Route::resource('/admindashboard', 'Admin\DashboardController');
// Route::resource('/adminfaq', 'Admin\FaqController');
Route::resource('/adminprofiles', 'Admin\ProfilesController');
Route::resource('/adminbusinesssetting', 'Admin\BusinesssettingController');
Route::resource('/admincategory','Admin\CategoryController');
Route::resource('/adminposts', 'Admin\PostsController');
Route::resource('/adminaboutus', 'Admin\AboutusController');
Route::resource('/admincontactus', 'Admin\ContactusController');
Route::resource('/adminhowitworks', 'Admin\HowitworksController');
Route::resource('/adminhomephotographers', 'Admin\HomephotographersController');
Route::resource('/adminhomecomingsoons', 'Admin\HomecomingsoonsController');
Route::resource('/postsevent', 'Admin\PosteventController');

Route::resource('/admincontacts', 'Admin\ContactsController');
// Route::get('/adminposts', 'PostsController@co_destroy')
Route::resource('/admincustomer', 'Admin\CustomersController');
Route::resource('/admincustomers', 'Admin\CustomerRegisterController');
Route::resource('/admincategory','Admin\CategoryController');
Route::get('/admincategory/{id}/edit/delete_image/{catgalleryid}','Admin\CategoryController@delete_image');

Route::resource('/adminclasses','Admin\ClassesController');
Route::get('/adminclasses/{id}/edit/delete_image/{pcgalleryid}','CategoryController@delete_image'); 
Route::resource('/adminorganiser','Admin\OrganiserController');
Route::resource('/adminaddons','Admin\AddonsController');
Route::resource('/adminvolunteers', 'Admin\VolunteersController');
Route::resource('/admineventbookings','Admin\EventbookingsController');
Route::resource('/ticket','Admin\TicketsController');
Route::resource('/adminclassbooking','Admin\ClassbookingController');
Route::resource('/orders','Admin\OrdersController');
Route::post('image/upload/store','UserbookingController@fileStore');
Route::get('/photographersession/{id}/index/pc_delete/{pgalleryid}','UserbookingController@pc_delete');
Route::get('/loadmore','UserbookingController@loadDataAjax');
Route::get('/notification/{id}','UserbookingController@notification');
Route::get('/notitysec', 'UserbookingController@updatenoti');
Route::get('/feedback/{id}','UserbookingController@feedback');
Route::get('/photogharnotify', 'UserbookingController@updatephotonotify');
Route::get('subscribe', 'NewsletterController@subscribe');
Route::post('classfeedback', 'UserbookingController@classfeedback');
Route::get('/usernotiy', 'UserbookingController@adminupdatenotiy');
Route::get('ticket/create/{id}', 'Admin\TicketsController@create')->name('ticket.create');
Route::get('ticket/edit/{id}', 'Admin\TicketsController@edit')->name('ticket.edit');
Route::get('ticket/index/{id}', 'Admin\TicketsController@index')->name('ticket.index');
Route::get('/organiserregistration', 'OrganiserregistrationController@index')->name('organiserregistration');
Route::post('/organiserregistration/insert', 'OrganiserregistrationController@insert');
Route::get('/customersregistration', 'CustomersregistrationController@index')->name('customersregistration');
Route::post('/customersregistration/insert', 'CustomersregistrationController@insert');
Route::resource('/organiserdashboard', 'Organiser\ProfileController');
Route::resource('/eventbookings','Admin\EventbookingsController');
Route::get('event-listings', 'EventListingController@index');
Route::post('event-listings', 'EventListingController@index');
Route::get('event-details/{eventName}', 'EventListingController@getEventDetails')->name('event-details.getEventDetails');
Route::get('/requestdata', 'UserbookingController@requestdata');
Route::get('/sendmail', 'Admin\PosteventController@sendmail');
Route::get('customerdata/index/{id}', 'Admin\CustomerdataController@index')->name('customerdata.index');
Route::get('exportorders', 'Admin\OrdersController@exportorders');
Route::get('exportcustomer/{id}', 'Admin\CustomerdataController@exportcustomer');
Route::get('cancelorder/{id}', 'Admin\OrdersController@cancelorder');
Route::resource('contact', 'ContactController');
Route::get('/onboard-prereq','OrganiserregistrationController@organiserOnBoarding')->name('onboard-prereq.organiserOnBoarding');
Route::get('/OnBoardingRedirect','OrganiserregistrationController@OnBoardingRedirect');

/************************ start discount************************/
Route::resource('/discounts','Admin\DiscountsController');
Route::get('discounts/index/{id}', 'Admin\DiscountsController@index')->name('discounts.index');
Route::get('discounts/create/{id}', 'Admin\DiscountsController@create')->name('discounts.create');
Route::get('/discountsticket/{id}', 'Admin\DiscountsController@discountsticket')->name('discountsticket');
Route::get('/earlybirddiscounts/{id}', 'Admin\DiscountsController@earlybirddiscounts')->name('earlybirddiscounts');
Route::get('/bundleofferdiscounts/{id}', 'Admin\DiscountsController@bundleofferdiscounts')->name('bundleofferdiscounts');
Route::get('/ticketxdiscounts/{id}', 'Admin\DiscountsController@ticketxdiscounts')->name('ticketxdiscounts');
Route::get('/discountsticketedit/{id}', 'Admin\DiscountsController@discountsticketedit')->name('discountsticketedit');
Route::get('/earlybirddiscountsedit/{id}', 'Admin\DiscountsController@earlybirddiscountsedit')->name('earlybirddiscountsedit');
Route::get('/bundleofferdiscountsedit/{id}', 'Admin\DiscountsController@bundleofferdiscountsedit')->name('bundleofferdiscountsedit');
Route::get('/ticketxdiscountsedit/{id}', 'Admin\DiscountsController@ticketxdiscountsedit')->name('ticketxdiscountsedit');

/************************ end discount************************/
/************************ start ticket discount************************/
Route::resource('/ticketcollabration','Admin\TicketcollabrationController');
Route::get('/collabration/{id}', 'Admin\TicketcollabrationController@collabration')->name('collabration');
Route::get('/selfevents', 'Admin\TicketcollabrationController@selfevents')->name('selfevents');
Route::get('/collabration_org/{id}', 'Admin\TicketcollabrationController@collabration_org')->name('collabration_org'); 

app/Http/Controllers/Admin/DashboardController.php
<?php
namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Auth;
use App\Admindashboard;
use App\Adminphotographers;
use App\Eventbookings;
use App\Classbookings;
use App\Photoclasses;
use App\Categories;
use App\Addons;
use App\Posts;
use App\Faqs;
use Session;
use DB;
use Hash;
use Image;
use App\Classes\ErrorsClass;
use App\Classes\CalendarClass;


class DashboardController extends Controller
{    

    public function __construct()
    {
        $this->middleware('auth');
    }

      public function index()
    {
         try { 
              $customers =  DB::table('users')
                               ->where('user_type', 3)
                               ->where('deleted', 0)
                               ->orderBy('id','DESC')
                               
                               ->get();  
                              

               $photographers = DB::table('users')
                               ->where('user_type', 4)
                               ->where('deleted', 0)
                               ->orderBy('id','DESC')
                               
                              ->get();

                $eventbookings = DB::table('eventbookings')
                               ->where('deleted', 0)
                               ->orderBy('id','DESC')
                                
                                ->get();

           
             $data_request =  DB::table('requestdata')
                            ->where('deleted', 0)
                           ->orderBy('id','DESC')
                           ->get(); 
                $topFiveCustomers=$customers->take(5); 
                $totalCustomersCount=count($customers); 
                $topFiveOrganisers=  $photographers->take(5);
                $totalOrganisersCount=count($photographers  );
                $topFiveEvents=$eventbookings->take(5);
                $totalEventCount=count($eventbookings);
                $data_request_Count=count($data_request);

             
             return view('Admin.Dashboard.index',compact('topFiveCustomers','totalCustomersCount','topFiveOrganisers','totalOrganisersCount','topFiveEvents','totalEventCount','data_request_Count'));
                

            } catch (\Illuminate\Database\QueryException $e) {
                $errorClass = new ErrorsClass();
                $errors = $errorClass->saveErrors($e);
            } catch (\Exception $e) {
               $errorClass = new ErrorsClass();
               $errors = $errorClass->saveErrors($e);
        }   
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $customer = User::findOrFail($id);
        $photographer = User::findOrFail($id);
        $eventbooking = Eventbookings::findOrFail($id);
         $classbooking = DB::table('classbookings')
                            ->where('id','=', $id)
                            ->where('status', '=', 1)
                            ->where('deleted', '=', 0)
                            ->first();
        $categories = Categories::findOrFail($id);

    
        $catgalleryimages = DB::table('catgallery')
                            ->where('cat_id', $id)
                            ->where('status', '=', 1)
                            ->where('deleted', '=', 0)
                            ->orderBy('id','DESC')
                            ->get(); 
        $photoclass = Photoclasses::findOrFail($id); 
                               
        $pcgalleryimages = DB::table('pcgallery')
                            ->where('pc_id', $id)
                            ->where('status', '=', 1)
                            ->where('deleted', '=', 0)
                            ->orderBy('id','DESC')
                            ->get();  
              $countries = DB::table('countries')
              ->get();

         $addon = Addons::findOrFail($id);                      


        return view('Admin.Dashboard.Show',compact('customers','photographer','eventbooking','classbooking','categories','catgalleryimages','photoclass','pcgalleryimages','addon','countries'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Admin/Dashboard/index.blade.php
@extends('layouts.userdefault')
@section('content')
<!--booking-sec-start-->
  <!--booking-sec-start-->
  <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="card card-stats">
                <div class="card-header card-header-warning card-header-icon">
                  <div class="card-icon">
                    <i class="fa fa-users" aria-hidden="true"></i>

                  </div>
                  <p class="card-category">Customers</p>
                  <h3 class="card-title">{{$totalCustomersCount}}
                    
                  </h3>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    
                    <a href="{{ url('/admincustomer')}}">View All</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                  <div class="card-icon">
                   <i class="fa fa-sitemap" aria-hidden="true"></i>

                  </div>
                  <p class="card-category">Organisers</p>
                  <h3 class="card-title">{{$totalOrganisersCount}}</h3>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons">date_range</i> Last 24 Hours
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="card card-stats">
                <div class="card-header card-header-danger card-header-icon">
                  <div class="card-icon">
                    <i class="fa fa-calendar" aria-hidden="true"></i>
                  </div>
                  <p class="card-category">Total Events</p>
                  <h3 class="card-title">{{$totalEventCount}}</h3>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="card card-stats">
                <div class="card-header card-header-info card-header-icon">
                  <div class="card-icon">
                    <i class="fa fa-database" aria-hidden="true"></i>



                  </div>
                  <p class="card-category">Data Requests</p>
                  <h3 class="card-title">{{$data_request_Count}}</h3>
                </div>
                <div class="card-footer">
                  <div class="stats">
                  
                    <a href="{{ url('/postsevent')}}">View All</a>
                  
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <div class="card">
                <div class="card-header card-header-tabs card-header-primary">
                 <h4 class="card-title">Customers</h4>
                  
                </div>
                <div class="card-body">
                 <table class="table table-hover">
               
                <thead>
                    <tr class="text-warning">
                        <th >Image</th>
                        <th >Name</th>
                        <th >Registered</th>
                        <th >Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(count($topFiveCustomers)>0)
                     @foreach ($topFiveCustomers as $customer)
                    <tr class="tabledata">

                        <td >
                        @if($customer->profile_picture!='') 
                        <img src="{{ url('public') }}/uploads/profileimages/{{ $customer->profile_picture }}" class="img-responsive" style="width: 40px; height: 30px;">
                         @else
                         <img src="{{ url('public') }}/images/avtar.jpg" style="width: 40px; height: 30px;">
                       @endif
                        
                      </td>
                       
                        <td >{{ $customer->first_name }}</td>
                    
                        <td >{{ \Carbon\Carbon::parse($customer->created_at)->format('d M Y')}}</td>
  
                      
                    <td class="action_btns 3"> 
                     <a class="tablebtn" href="{{ route('admincustomer.show',$customer->id) }}" title="Show" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-eye"></i></a>  </td>                     
                    </tr>
                     @endforeach
                     @else
                    
                    @endif

        </tbody>
      </table>

                </div>
              </div>
            </div>
            <div class="col-lg-6 col-md-12">
              <div class="card">
                <div class="card-header card-header-warning">
                  <h4 class="card-title">Organisers</h4>
                  
                </div>
                <div class="card-body table-responsive">
                  <table class="table table-hover">
                <thead >
                    <tr class="text-warning">
                       <th> Image</th>
                        <th >Name</th>
                       
                        <th >Registered</th>
                       
                        <th >Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(count($topFiveOrganisers)>0)
                     @foreach ($topFiveOrganisers as $photographer)
                    <tr class="tabledata">

                      <td >
                        @if($photographer->profile_picture!='') 
                        <img src="{{ url('public') }}/uploads/profileimages/{{ $photographer->profile_picture }}" class="img-responsive" style="width: 40px; height: 30px;">
                         @else
                        <img src="{{ url('public') }}/images/avtar.jpg" style="width: 40px; height: 30px;">
                       @endif
                        
                      </td>
                        
                        <td >{{ $photographer->first_name }}</td>
                       
                       
                       
                        <td >{{ \Carbon\Carbon::parse($photographer->created_at)->format('d M Y')}}</td>
                       
                        

                    <td class="action_btns 2"> 
                    
                     <a class="tablebtn" href="{{ route('adminorganiser.show',$photographer->id) }}" title="Show" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-eye"></i></a>
                    
                    </td>
                       
                    </tr>
                     @endforeach
                     @else
                     
                    @endif

        </tbody>
      </table>
                </div>
              </div>
            </div>
          </div>

       

 
@endsection